const express = require('express')
const mongoose = require('mongoose')
const dotEnv = require('dotenv')
const cors = require('cors')
const studentRoute=require('./routes/StudentRoutes')
const teacherRoute = require('./routes/TeacherRoutes')
const permissionRoute= require('./routes/PermissionRoutes')
const app = express()
const PORT = process.env.PORT || 5000
dotEnv.config()
app.use(express.json())
app.use(cors())
app.use('/student',studentRoute)
app.use('/teacher',teacherRoute)
app.use('/permission',permissionRoute)
mongoose.connect(process.env.Mongoose_key)
    .then(() => console.log("Connected to database"))
    .catch((error) => console.log("Database connection error:", error))

app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`)
})